export const ADD_CONSTRUCTOR_ITEM = "ADD_CONSTRUCTOR_ITEM";
export const DELETE_CONSTRUCTOR_ITEM = "DELETE_CONSTRUCTOR_ITEM";
export const ADD_BUN = "ADD_BUN";
export const MOVE_ITEM = "MOVE_ITEM";
export const REFRESH_CONSTRUCTOR = "REFRESH_CONSTRUCTOR";
